name: API Manager UI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.event.number }}
jobs:
  build-product:
    runs-on: ubuntu-latest
    steps:
      - name: Run hostname
        run: hostname
      - name: Fix host entry
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Show hosts
        run: cat /etc/hosts
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: '10'
          path: apim-apps
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build apim-apps with Test.
        run: mvn clean install --file apim-apps/pom.xml
      - name: Get apim.apps.version
        run: mvn help:evaluate -Dexpression=project.version -q --file apim-apps/pom.xml -DforceStdout > ../APIM_APPS_VERSION_FILE
      - name: Print apim.apps.version
        run: |
          echo $(cat ../APIM_APPS_VERSION_FILE)
      - name: Download latest API Manager pack
        run: |
          wget 'https://wso2.org/jenkins/job/products/job/product_apim/job/product-apim/lastStableBuild/org.wso2.am$wso2am/artifact/org.wso2.am/wso2am/4.6.0-SNAPSHOT/wso2am-4.6.0-SNAPSHOT.zip'
      - name: Prepare APIM pack with built portals and configurations
        run: |
          unzip wso2am-4.6.0-SNAPSHOT.zip
          rm -rf wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/publisher
          rm -rf wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/devportal
          rm -rf wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/admin
          cp -r apim-apps/portals/publisher/target/publisher.war wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/
          cp -r apim-apps/portals/devportal/target/devportal.war wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/
          cp -r apim-apps/portals/admin/target/admin.war wso2am-4.6.0-SNAPSHOT/repository/deployment/server/webapps/
          printf "\n[apim.devportal]\nenable_application_sharing = true\napplication_sharing_type = \"default\"\n" >> wso2am-4.6.0-SNAPSHOT/repository/conf/deployment.toml
      - name: start APIM server
        run: |
          sh wso2am-4.6.0-SNAPSHOT/bin/api-manager.sh start
          sleep 5m # sleep for 5 min to start the server
          nc -zv localhost 9443
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: false
          working-directory: 'apim-apps/tests'
          spec: '**/*.spec.js'
      - name: Upload ScreenShots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apim-apps/tests/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: apim-apps/tests/cypress/videos
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: server-logs
          path: wso2am-*/repository/logs
